import { useEffect, useState } from 'react';

export const Badge = ({ children }) => <span className={`badge ${String(children || '').toLowerCase().replaceAll('_', '-')}`}>{String(children || 'UNKNOWN').replaceAll('_', ' ')}</span>;
export function Spinner({ label = 'Loading data…' }) { return <div className="loading" role="status"><i />{label}</div>; }
export function Empty({ title = 'Nothing to show', children }) { return <div className="empty"><b>□</b><h3>{title}</h3>{children && <p>{children}</p>}</div>; }
export function ErrorState({ text, retry }) { return <div className="error-state"><h3>We could not load this data</h3><p>{text}</p>{retry && <button onClick={retry}>Try again</button>}</div>; }
export function Toast({ message, onClose }) { useEffect(() => { const timer = setTimeout(onClose, 4500); return () => clearTimeout(timer); }, [onClose]); return <div className="toast" role="status">{message}<button aria-label="Dismiss notification" onClick={onClose}>×</button></div>; }
export function Modal({ title, children, onClose }) { return <div className="modal-backdrop" onMouseDown={onClose} role="presentation"><section className="modal" role="dialog" aria-modal="true" aria-label={title} onMouseDown={event => event.stopPropagation()}><header><h2>{title}</h2><button className="icon-button" aria-label="Close" onClick={onClose}>×</button></header>{children}</section></div>; }
export function ConfirmDialog({ title, message, action, tone = 'danger', onClose }) { return <Modal title={title} onClose={onClose}><p>{message}</p><div className="dialog-actions"><button className="outline" onClick={onClose}>Cancel</button><button className={tone} onClick={action}>Confirm</button></div></Modal>; }
export function Stat({ label, value, tone = 'blue', detail }) { return <article className={`stat ${tone}`}><span>{label}</span><strong>{value ?? '—'}</strong>{detail && <small>{detail}</small>}</article>; }
export function Timeline({ status }) { const steps = ['DRAFT', 'SUBMITTED', 'ASSIGNED', 'IN_VERIFICATION', 'CERTIFICATE_ISSUED']; const active = Math.max(0, steps.indexOf(status)); return <div className="timeline" aria-label={`Application status: ${status}`}>{steps.map((step, index) => <div className={index <= active ? 'done' : ''} key={step}><b>{index + 1}</b><span>{step.replaceAll('_', ' ')}</span></div>)}</div>; }
export function useAsync(load, deps = []) { const [state, setState] = useState({ loading: true, data: null, error: '' }); useEffect(() => { let live = true; setState({ loading: true, data: null, error: '' }); load().then(data => live && setState({ loading: false, data, error: '' })).catch(error => live && setState({ loading: false, data: null, error: error.message })); return () => { live = false; }; }, deps); return state; }
